export const AuthenType = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP'
}

export const Actions = {
  CURRENT_USER_LOADING: 'CURRENT_USER_LOADING',
  CURRENT_USER_SUCCESS: 'CURRENT_USER_SUCCESS',

  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',

  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL'
}
